


artifacts_root : artifacts



prepare_base_model :
  root_dir : artifacts/prepare_base_model
  base_model_path : artifacts/prepare_base_model/base_model.keras
  updated_base_model_path : artifacts/prepare_base_model/updated_base_model.keras