


artifacts_root : artifacts



data_ingestion : 
  root_dir : artifacts/data_ingestion
  local_data_path : artifacts/data_ingestion/data



prepare_base_model :
  root_dir : artifacts/prepare_base_model
  base_model_path : artifacts/prepare_base_model/base_model.keras
  updated_base_model_path : artifacts/prepare_base_model/updated_base_model.keras




training :
  root_dir : artifacts/training
  trained_model_path : artifacts/training/trained_model.keras
  training_data_path :  artifacts/data_ingestion/data




evaluation : 
  root_dir : artifacts/evaluation
  trained_model_path : artifacts/training/trained_model.keras
  training_data_path : artifacts/data_ingestion/data

